---
name: Pre-commit
description: Check that pre-commit is required
runs:
    using: "composite"
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install ".[dev]"
        shell: bash

      - name: Run pre-commit
        run: pre-commit run --all-files
        shell: bash
