[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
pattern = "default-unprefixed"

[tool.poetry.dependencies]
python = "^3.7"

# Python lack of functionalities from future versions
importlib-metadata = { version = "*", python = "<3.8" }
typing-extensions = ">=3.10.0"

# Missing compatibility layer between Python 2 and Python 3
six = ">=1.12.0"
future = ">=0.17.1"

# Utility
packaging = "*"
click = ">=7.0"

# Networking
bravado = "^11.0.0"
oauthlib = ">=2.1.0"
PyJWT = "*"
requests = ">=2.20.0"
requests-oauthlib = ">=1.0.0"
websocket-client = ">=0.35.0, !=1.0.0"
urllib3 = "*"
swagger-spec-validator = ">=2.7.4"

# Built-in integrations
boto3 = ">=1.28.0"
Pillow = ">=1.1.6"
GitPython = ">=2.0.8"
psutil = "*"
pandas = "*"

# Additional integrations
kedro-neptune = { version = "*", optional = true, python = "<3.11" }
neptune-detectron2 = { version = "*", optional = true, python = ">=3.7"}
neptune-fastai = { version = "*", optional = true }
neptune-lightgbm = { version = "*", optional = true }
pytorch-lightning = { version = "*", optional = true }
neptune-optuna = { version = "*", optional = true }
neptune-prophet = { version = "*", optional = true }
neptune-pytorch = { version = "*", optional = true }
neptune-sacred = { version = "*", optional = true }
neptune-sklearn = { version = "*", optional = true }
neptune-tensorflow-keras = { version = "*", optional = true }
neptune-tensorboard = { version = "*", optional = true }
neptune-xgboost = { version = "*", optional = true }
transformers = { version = "*", optional = true }
zenml = { version = "*", optional = true }
mosaicml = { version = "*", optional = true }
neptune-aws = { version = "*", optional = true }
neptune-mlflow = { version = "*", optional = true }
neptune-airflow = { version = "*", optional = true }

[tool.poetry.extras]
aws = ["neptune-aws"]
detectron2 = ["neptune-detectron2"]
fastai = ["neptune-fastai"]
kedro = ["kedro-neptune"]
lightgbm = ["neptune-lightgbm"]
optuna = ["neptune-optuna"]
prophet = ["neptune-prophet"]
pytorch = ["neptune-pytorch"]
pytorch-lightning = ["pytorch-lightning"]
sacred = ["neptune-sacred"]
sklearn = ["neptune-sklearn"]
tensorflow-keras = ["neptune-tensorflow-keras"]
tensorboard = ["neptune-tensorboard"]
transformers = ["transformers"]
xgboost = ["neptune-xgboost"]
zenml = ["zenml"]
mosaicml = ["mosaicml"]
mlflow = ["neptune-mlflow"]
airflow = ["neptune-airflow"]
experimental = ["neptune-experimental"]

[tool.poetry]
authors = ["neptune.ai <contact@neptune.ai>"]
description = "Neptune Client"
repository = "https://github.com/neptune-ai/neptune-client"
homepage = "https://neptune.ai/"
documentation = "https://docs.neptune.ai/"
include = ["CHANGELOG.md"]
license = "Apache License 2.0"
name = "neptune-client"
readme = "README.md"
version = "1.0.0"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
keywords = [
    "MLOps",
    "ML Experiment Tracking",
    "ML Model Registry",
    "ML Model Store",
    "ML Metadata Store",
]
packages = [
    { include = "neptune", from = "src" },
]

[tool.poetry.urls]
"Tracker" = "https://github.com/neptune-ai/neptune-client/issues"
"Documentation" = "https://docs.neptune.ai/"

[tool.poetry.scripts]
neptune = "neptune.cli.__main__:main"
