# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: values.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvalues.proto\x12\x08tutorial\"\x80\x01\n\x12\x46loatPointValueDTO\x12\x1c\n\x0ftimestampMillis\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x11\n\x04step\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\x01H\x02\x88\x01\x01\x42\x12\n\x10_timestampMillisB\x07\n\x05_stepB\x08\n\x06_value\"t\n\x14\x46loatSeriesValuesDTO\x12,\n\x06values\x18\x01 \x03(\x0b\x32\x1c.tutorial.FloatPointValueDTO\x12\x1b\n\x0etotalItemCount\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x11\n\x0f_totalItemCountb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'values_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOATPOINTVALUEDTO._serialized_start=27
  _FLOATPOINTVALUEDTO._serialized_end=155
  _FLOATSERIESVALUESDTO._serialized_start=157
  _FLOATSERIESVALUESDTO._serialized_end=273
# @@protoc_insertion_point(module_scope)
