---
name: Test E2E
description: Check client against production API
inputs:
  sa-api-token:
     description: "Api token for service account"
     required: true
  user-api-token:
     description: "Api token for regular user"
     required: true
  aws-access-key-id:
     description: "S3 access key for AWS service"
     required: true
  aws-secret-access-key:
     description: "S3 access key for AWS service"
     required: true
  gcs-access-key-id:
     description: "S3 access key for GCS service"
     required: true
  gcs-secret-access-key:
     description: "S3 access key for GCS service"
     required: true
runs:
    using: "composite"
    steps:
      - name: Install package
        uses: ./.github/actions/package
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test Fast.ai integration
        uses: neptune-ai/neptune-fastai/.github/actions/e2e@master
        with:
          working_directory: neptune_fastai
        env:
          NEPTUNE_API_TOKEN: ${{ inputs.user-api-token}}
          NEPTUNE_PROJECT: e2e-tests/e2e

      - name: Test Kedro integration
        uses: neptune-ai/kedro-neptune/.github/actions/e2e@main
        with:
          working_directory: neptune_kedro
        env:
          NEPTUNE_API_TOKEN: ${{ inputs.user-api-token}}
          NEPTUNE_PROJECT: e2e-tests/kedro-neptune-e2e

      - name: Test Prophet integration
        uses: neptune-ai/neptune-prophet/.github/actions/e2e@main
        with:
          working_directory: neptune_prophet
        env:
          NEPTUNE_API_TOKEN: ${{ inputs.user-api-token}}
          NEPTUNE_PROJECT: e2e-tests/e2e

      - name: Test Keras integration
        uses: neptune-ai/neptune-tensorflow-keras/.github/actions/e2e@master
        with:
          working_directory: neptune_keras
        env:
          NEPTUNE_API_TOKEN: ${{ inputs.user-api-token}}
          NEPTUNE_PROJECT: e2e-tests/e2e
