---
name: Publish tests
description: Check python code
runs:
    using: "composite"
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-artifacts
          path: ./test-results

      - name: Display test artifacts
        run: ls -R ./test-results
        shell: bash

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "**/test-results/test-*.xml"
