---
name: Notify about job status
description: Send Slack channel notification about job finish status
inputs:
  slack-webhook:
    description: "A Slack Webhook to post a notification"
    required: true
  job-status:
    description: "Finish status of a preceding job"
    required: true


runs:
  using: "composite"
  steps:
    - name: Notify about failure
      uses: 8398a7/action-slack@v3
      if: ${{ inputs.job-status != 'success' }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook }}
      with:
        status: failure
        fields: repo,message,author,job,eventName,took

    - name: Notify about success
      uses: 8398a7/action-slack@v3
      if: ${{ inputs.job-status == 'success' }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook }}
      with:
        status: success
        fields: repo,message,author,job,eventName,took
