---
name: Test E2E
description: Check client against production API
inputs:
  python-version:
    description: "Python version"
    required: true
  module:
    description: "Module"
    required: true
  os:
    description: "Operating system"
    required: true
  name:
    description: "Name"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install package
      uses: ./.github/actions/package
      with:
        python-version: ${{ inputs.python-version }}

    - name: E2E - ${{ inputs.module }}
      run: |
        pytest -v ./e2e_tests -m "${{ inputs.module }}" \
        --timeout=600 --timeout_method=thread \
        --junitxml="./test-results/test-e2e-${{ inputs.name }}${{ inputs.module }}-${{ inputs.os }}-${{ matrix.python-version }}.xml"
      shell: bash

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-artifacts
        path: ./test-results
