---
name: Test Integration E2E
description: Check client against production API
inputs:
  python-version:
    description: "Python version"
    required: true
  module:
    description: "Module"
    required: true
  os:
    description: "Operating system"
    required: true
  name:
    description: "Name"
    required: false
    default: ""
  report_job:
    description: "Job name to update by JUnit report"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install package
      uses: ./.github/actions/install-package
      with:
        python-version: ${{ inputs.python-version }}
        os: ${{ inputs.os }}
        extras: integrations-e2e

    - name: Integration - ${{ inputs.module }}
      run: |
        pytest -v ./tests/integrations/ -m "${{ inputs.module }}" \
        --timeout=600 --timeout_method=thread \
        --color=yes \
        --junitxml="./test-results/test-integration-${{ inputs.name }}-${{ inputs.module }}-${{ inputs.os }}-${{ inputs.python-version }}.xml"
      shell: bash

    - name: Report
      uses: mikepenz/action-junit-report@v3.6.2
      if: always()
      with:
        report_paths: './test-results/test-integration-*.xml'
        update_check: true
        include_passed: true
        annotate_notice: true
        job_name: ${{ inputs.report_job }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-artifacts
        path: ./test-results
