# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x15neptune.ingest.v1.pub\"\x1a\n\tRequestId\x12\r\n\x05value\x18\x01 \x01(\tB3\n\x1cml.neptune.client.api.modelsB\x11\x43lientIngestProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034ml.neptune.client.api.modelsB\021ClientIngestProtoP\001'
  _globals['_REQUESTID']._serialized_start=39
  _globals['_REQUESTID']._serialized_end=65
# @@protoc_insertion_point(module_scope)
