---
name: Test E2E
description: Check client against production API
inputs:
  python-version:
    description: "Python version"
    required: true
  module:
    description: "Module"
    required: true
  os:
    description: "Operating system"
    required: true
  name:
    description: "Name"
    required: false
    default: ""
  report-job:
    description: "Job name to update by JUnit report"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install package
      uses: ./.github/actions/install-package
      with:
        python-version: ${{ inputs.python-version }}
        os: ${{ inputs.os }}

    - name: E2E - ${{ inputs.module }}
      run: |
        coverage run -p -m \
        pytest -v ./tests/e2e/ -m "${{ inputs.module }}" \
        --timeout=600 --timeout_method=thread \
        --junitxml="./test-results/test-e2e-${{ inputs.name }}-${{ inputs.module }}-${{ inputs.os }}-${{ inputs.python-version }}.xml"
      shell: bash

    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: e2e-coverage
        path: ./.coverage*

    - name: Report
      uses: mikepenz/action-junit-report@v3.6.2
      if: always()
      with:
        report_paths: './test-results/test-e2e-*.xml'
        update_check: true
        include_passed: true
        annotate_notice: true
        job_name: ${{ inputs.report-job }}

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-artifacts
        path: ./test-results
