---
name: Test E2E
description: Check client against production API
inputs:
  python-version:
    description: "Python version"
    required: true
  module:
    description: "Module"
    required: true
  os:
    description: "Operating system"
    required: true
  name:
    description: "Name"
    required: true
  report_job:
    description: "Job name to update by JUnit report"
    required: true
  codecov-token:
    description: "Codecov token"
    required: false
    default: ""
  pip_url:
    description: "Pip URL for integration installation"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install package
      uses: ./.github/actions/install-package
      with:
        python-version: ${{ inputs.python-version }}
        os: ${{ inputs.os }}-latest
        pip_url: ${{ inputs.pip_url }}

    - name: E2E - ${{ inputs.module }}
      run: |
        pytest --cov=neptune --cov-report xml \
        -v ./tests/e2e/ -m "${{ inputs.module }}" \
        --timeout=600 --timeout_method=thread \
        --color=yes \
        --junitxml="./test-results/test-e2e-${{ inputs.name }}-${{ inputs.module }}-${{ inputs.os }}-${{ inputs.python-version }}.xml"
      shell: bash

    - name: Report
      uses: mikepenz/action-junit-report@v3.6.2
      if: always()
      with:
        report_paths: './test-results/test-e2e-*.xml'
        update_check: true
        include_passed: true
        annotate_notice: true
        job_name: ${{ inputs.report_job }}

    - name: Upload Pull Request coverage report do Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        files: ./coverage.xml
        flags: e2e,e2e-${{ inputs.name }},${{ inputs.os }},py${{ inputs.python-version }}
        fail_ci_if_error: false

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-artifacts
        path: ./test-results
