---
name: Test Unit
description: Check unit tests
inputs:
  python-version:
    description: "Python version"
    required: true
  os:
    description: "Operating system"
    required: true
  report_job:
    description: "Job name to update by JUnit report"
    required: true
  codecov-token:
    description: "Codecov token"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install package
      uses: ./.github/actions/install-package
      with:
        python-version: ${{ inputs.python-version }}
        os: ${{ inputs.os }}-latest

    - name: Test
      run: |
        pytest --cov=neptune --cov-report xml \
        -v -n 2 ./tests/unit/ \
        --timeout=120 --timeout_method=thread \
        --color=yes \
        --junitxml="./test-results/test-unit-new-${{ inputs.os }}-${{ inputs.python-version }}.xml"
      shell: bash

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-artifacts
        path: ./test-results

    - name: Upload Pull Request coverage report do Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        files: ./coverage.xml
        flags: unit,${{ inputs.os }},py${{ inputs.python-version }}
        fail_ci_if_error: false

    - name: Report
      uses: mikepenz/action-junit-report@v3.6.2
      if: always()
      with:
        report_paths: './test-results/test-unit-*.xml'
        update_check: true
        include_passed: true
        annotate_notice: true
        job_name: ${{ inputs.report_job }}
