---
name: Lint
description: Check style for every file
runs:
    using: "composite"
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        uses: ./.github/actions/dependencies

      - name: Run pre-commit
        run: pre-commit run --all-files
        shell: bash

      - name: Lint
        run: python -m pylint -j 0 -f parseable neptune tests
        shell: bash
