---
name: Coverage
inputs:
  token:
     description: "Codecov token"
     required: true
  kind:
     description: "Test kind (e2e or unit)"
     required: true
description: Gather and report coverage to Codecov
runs:
    using: "composite"
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install coverage
        run: |
          pip install coverage[toml]
        shell: bash

      - name: Download coverages
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.kind }}-coverage
          path: ./

      - name: Combine coverages
        run: coverage combine
        shell: bash

      - name: Show coverage report
        run: coverage report -m
        shell: bash

      - name: Prepare coverage report
        run: coverage xml
        shell: bash

      - name: Upload coverage report do Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ inputs.token }}
          files: ./coverage.xml
          flags: ${{ inputs.kind }}
          fail_ci_if_error: false
