---
name: Package
description: Install python and package
inputs:
  python-version:
    description: "Python version"
    required: true
  os:
    description: "Operating system"
    required: true
  dependencies-group:
    description: "Install only specific dependencies group"
    required: false
    default: "all"
  poetry-version:
    description: "Poetry version"
    required: false
    default: "1.4.0"

runs:
    using: "composite"
    steps:
#      - name: Get current date
#        id: date
#        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
#        shell: bash
#
##      - uses: actions/cache@v3
##        id: cache
##        with:
##          path: ~/.cache/pypoetry
##          key: ${{ inputs.dependencies-group }}-${{ inputs.os }}-python-${{ inputs.python-version }}-${{ inputs.poetry-version }}-${{ hashFiles('pyproject.toml') }}-${{ steps.date.outputs.date }}

      - name: Install Poetry
        run: |
          pipx install poetry
        shell: bash

      - name: Install Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Install dependencies
        run: |
          if [ "${{ inputs.dependencies-group }}" = "dev" ]; then
              poetry install --extras "dev"
          else
              poetry install --extras "dev e2e"
          fi
        shell: bash

      - name: List dependencies
        run: |
          poetry run pip list
        shell: bash
