name: dev-test-slack-notif

on:
  workflow_dispatch:

env:
  WORKSPACE_NAME: ${{ vars.E2E_WORKSPACE_NAME }}
  BUCKET_NAME: ${{ secrets.E2E_BUCKET_NAME }}
  USER_USERNAME: ${{ vars.E2E_USER_USERNAME }}
  NEPTUNE_API_TOKEN: ${{ secrets.E2E_USER_API_TOKEN }}
  ADMIN_USERNAME: ${{ vars.E2E_ADMIN_USERNAME }}
  ADMIN_NEPTUNE_API_TOKEN: ${{ secrets.E2E_ADMIN_API_TOKEN }}
  SERVICE_ACCOUNT_NAME: ${{ vars.E2E_SERVICE_ACCOUNT_NAME }}

jobs:
  dev-tests-notify:
    runs-on: ubuntu-latest
    if: (success() || failure())
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Notify
        uses: ./.github/actions/dev-workflow-notify
        with:
          slack-webhook: ${{ secrets.E2E_REGULAR_SLACK_WEBHOOK }}
