name: Minimal E2E
on: [workflow_dispatch]
jobs:
  test-e2e:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 75
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    env:
      WORKSPACE_NAME: e2e-tests
      BUCKET_NAME: ${{ secrets.E2E_BUCKET_NAME }}
      USER_USERNAME: ${{ secrets.E2E_USER_USERNAME }}
      ADMIN_USERNAME: ${{ secrets.E2E_ADMIN_USERNAME }}
      ADMIN_NEPTUNE_API_TOKEN: ${{ secrets.E2E_ADMIN_NEPTUNE_API_TOKEN }}
      SERVICE_ACCOUNT_NAME: ${{ secrets.E2E_SERVICE_ACCOUNT_NAME }}
      # Time before went into offline mode
      # Default is 1 minute, and it made most of the tests to failure
      # as it takes some time to create project and all internal structures
      NEPTUNE_RETRIES_TIMEOUT: 1200
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Some tests are checking version of 'neptune' package.
          # To simplify deployment we're using 'versioneer' but
          # when working with branches it yields "0+unknown".
          # Fetching all history fetches also last tag and helps versioneer
          fetch-depth: 0

      - name: Tests E2E
        uses: ./.github/actions/tests-e2e
        with:
          sa-api-token: ${{secrets.E2E_SERVICE_ACCOUNT_API_TOKEN}}
          user-api-token: ${{secrets.E2E_NEPTUNE_API_TOKEN}}
          aws-access-key-id: ${{secrets.E2E_AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.E2E_AWS_SECRET_ACCESS_KEY}}
          gcs-access-key-id: ${{secrets.E2E_GCS_ACCESS_KEY_ID}}
          gcs-secret-access-key: ${{secrets.E2E_GCS_SECRET_ACCESS_KEY}}

  publish-tests:
    needs: [test-e2e]
    runs-on: ubuntu-latest
    if: always()
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish tests
        uses: ./.github/actions/publish-tests-result
