name: mypy

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master

jobs:
  test:
    timeout-minutes: 75
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install package
        uses: ./.github/actions/install-package
        with:
          python-version: "3.7"
          os: ubuntu-latest

      - name: Run mypy
        run: mypy --config-file pyproject.toml
