name: Compatibility Package

on:
  workflow_dispatch:
  push:
    branches:
      - compatibility-package
      - rj/compatibility-package-added  # TODO: Remove

jobs:
  test:
    timeout-minutes: 75
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install "."

      - name: List dependencies
        run: pip list

      - name: Run tests
        run: python -c "from neptune import init_run"
